"""``_normalize_ddl`` 字符串级单测 —— 零 PG 依赖,进默认套件。

回归背景:把 ``INTEGER PRIMARY KEY AUTOINCREMENT`` 翻成不带 PK 的
``IDENTITY`` 时,``REFERENCES users(id)`` 的外键表在 PG 上会因「被引用列
没有 PK/UNIQUE 约束」而建不出来(42830);SQLite 测试全程无感,只有真机
PG 才炸,所以这里用字符串级断言把「PK 必须留在列上」钉死。
"""

from __future__ import annotations

from trove.services.auth.store import (
    AUDIT_LOG_TABLE_SQL,
    LOGIN_ATTEMPTS_TABLE_SQL,
    TOKENS_TABLE_SQL,
    USER_DATASOURCES_TABLE_SQL,
    USERS_TABLE_SQL,
)
from trove.storage.backends.postgres import _normalize_ddl

_AUTH_DDLS = [
    USERS_TABLE_SQL,
    TOKENS_TABLE_SQL,
    USER_DATASOURCES_TABLE_SQL,
    AUDIT_LOG_TABLE_SQL,
    LOGIN_ATTEMPTS_TABLE_SQL,
]


def test_autoincrement_translates_to_identity_with_primary_key():
    out = _normalize_ddl("id INTEGER PRIMARY KEY AUTOINCREMENT,")
    assert "AUTOINCREMENT" not in out.upper()
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out.upper()


def test_auth_tables_preserve_every_primary_key():
    """翻译不得吞掉任何 PRIMARY KEY(PK 计数是翻译前后不变量)。"""
    for ddl in _AUTH_DDLS:
        out = _normalize_ddl(ddl)
        assert "AUTOINCREMENT" not in out.upper()
        assert out.upper().count("PRIMARY KEY") == ddl.upper().count("PRIMARY KEY")


def test_plain_integer_primary_key_untouched():
    ddl = "id INTEGER PRIMARY KEY,"
    assert _normalize_ddl(ddl) == ddl
