"""PostgreSQL storage backend — production backend for Trove's internal state.

Implements :class:`StorageBackend` over psycopg (async). The backend owns the
dialect translation the stores previously got for free from aiosqlite:

- ``?`` placeholders → ``%s`` (parameter style);
- ``INTEGER PRIMARY KEY AUTOINCREMENT`` → ``INTEGER GENERATED BY DEFAULT AS
  IDENTITY`` (SQLite shorthand used by the stores' DDL);
- ``lastrowid`` → INSERTs are rewritten to append ``RETURNING <pk>`` and the
  returned row's first column is materialized as ``cursor.lastrowid``;
- ``executescript`` → statements are run one at a time (psycopg runs the
  script in a single execute; we split on ``;`` for compatibility with
  idempotent ``CREATE ... IF NOT EXISTS`` scripts).

A single backend instance maps to one database (DSN). Test isolation is
achieved with per-test **schemas** (``schema`` param sets ``search_path``),
so the same tables live in independent namespaces.
"""

from __future__ import annotations

import re
from typing import Any, AsyncIterator

from trove.storage.backends.base import StorageBackend, StorageCursor

# SQLite 表定义里用到的方言片段 → PG 等价物。
_AUTOINC_RE = re.compile(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE)
_PK_RE = re.compile(r"INTEGER\s+PRIMARY\s+KEY", re.IGNORECASE)

# SQLite 的 INSERT OR REPLACE / INSERT OR IGNORE → PG 的 ON CONFLICT 形态。
_INSERT_OR_REPLACE_RE = re.compile(
    r"\bINSERT\s+OR\s+REPLACE\s+INTO\b", re.IGNORECASE)
_INSERT_OR_IGNORE_RE = re.compile(
    r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.IGNORECASE)

_RETURNING_RE = re.compile(r"\bRETURNING\b", re.IGNORECASE)
_LAST_INSERT_RE = re.compile(r"^\s*INSERT\s+INTO\b", re.IGNORECASE)


def _normalize_ddl(sql: str) -> str:
    """SQLite 方言 DDL → PG 等价形式(仅替换已知片段,其余原样)。"""
    sql = _AUTOINC_RE.sub("INTEGER GENERATED BY DEFAULT AS IDENTITY", sql)
    sql = _INSERT_OR_REPLACE_RE.sub("INSERT INTO", sql)
    sql = _INSERT_OR_IGNORE_RE.sub("INSERT INTO", sql)
    return sql


def _translate_placeholders(sql: str) -> str:
    """``?`` → ``%s``,跳过单引号字符串与注释内的 ``?``。

    psycopg 用 ``%s`` 占位;store 代码保持 ``?``(跨后端可移植)。
    遍历字符,单引号内(含 ``''`` 转义)与 ``--``/``/* */`` 注释内的
    ``?`` 不替换。
    """
    out: list[str] = []
    i, n = 0, len(sql)
    in_single = False
    in_line_comment = False
    in_block_comment = False
    while i < n:
        ch = sql[i]
        nxt = sql[i + 1] if i + 1 < n else ""
        if in_line_comment:
            out.append(ch)
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            out.append(ch)
            if ch == "*" and nxt == "/":
                out.append(nxt)
                in_block_comment = False
                i += 2
            else:
                i += 1
            continue
        if ch == "-" and nxt == "-":
            in_line_comment = True
            out.append(ch)
            out.append(nxt)
            i += 2
            continue
        if ch == "/" and nxt == "*":
            in_block_comment = True
            out.append(ch)
            out.append(nxt)
            i += 2
            continue
        if ch == "'":
            in_single = not in_single
            out.append(ch)
            i += 1
            continue
        if ch == "?" and not in_single:
            out.append("%s")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def _rewrite_insert(sql: str, need_lastrowid: bool) -> tuple[str, bool]:
    """为需要 lastrowid 的 INSERT 追加 ``RETURNING <pk>``。

    Returns ``(sql, needs_returning)`` — 仅当调用方显式声明
    ``need_lastrowid=True`` 且语句为 INSERT 且未显式 RETURNING 时追加。
    盲加会破坏无 ``id`` 列的表(如 settings 主键为 key)。
    """
    if not need_lastrowid or not _LAST_INSERT_RE.match(sql):
        return sql, False
    if _RETURNING_RE.search(sql):
        return sql, False
    return f"{sql.rstrip().rstrip(';')} RETURNING id", True


class _NamedTupleRow:
    """同时支持按名(``row['col']``)与按位置(``row[0]``)访问的 row。

    对齐 aiosqlite.Row 的访问语义:KB/检索 store 用 ``row['name']``,
    其他 store 用 ``row[0]``。psycopg 的自定义 row_factory 需要返回
    可迭代对象,tuple 子类天然满足。
    """

    __slots__ = ("_data", "_names")

    def __init__(self, data: tuple, names: tuple[str, ...]):
        self._data = data
        self._names = names

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._data[key]
        return self._data[self._names.index(key)]

    def __iter__(self):
        return iter(self._data)

    def __len__(self):
        return len(self._data)

    def __repr__(self):
        return repr(self._data)

    def keys(self):
        return self._names

    def get(self, key, default=None):
        try:
            return self[key]
        except (ValueError, IndexError):
            return default


def _named_row_factory(cursor):
    """psycopg 自定义 row_factory:tuple + 列名 → _NamedTupleRow。"""
    names = tuple(d.name for d in cursor.description) if cursor.description else ()
    return lambda values: _NamedTupleRow(tuple(values), names)


class _PgCursor(StorageCursor):
    """psycopg AsyncCursor 适配:暴露 lastrowid/rowcount + 兼容 fetch API。"""

    def __init__(self, cur: Any, lastrowid: int | None = None):
        self._cur = cur
        self._lastrowid = lastrowid

    @property
    def lastrowid(self) -> int | None:
        return self._lastrowid

    @property
    def rowcount(self) -> int:
        return self._cur.rowcount

    async def fetchone(self) -> tuple | None:
        return await self._cur.fetchone()

    async def fetchall(self) -> list[tuple]:
        return await self._cur.fetchall()

    def __aiter__(self) -> AsyncIterator[tuple]:
        return self._cur.__aiter__()

    async def __aenter__(self) -> "_PgCursor":
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self._cur.close()


class PostgresBackend(StorageBackend):
    """One Postgres database, ``?``-placeholder SQL, RETURNING-based lastrowid."""

    def __init__(self, dsn: str, schema: str | None = None):
        self._dsn = dsn
        self._schema = schema
        self._conn: Any = None

    async def _connect(self) -> None:
        if self._conn is not None and not self._conn.closed:
            return
        import psycopg
        self._conn = await psycopg.AsyncConnection.connect(
            self._dsn, row_factory=_named_row_factory,
        )
        if self._schema:
            await self._conn.execute(
                f'CREATE SCHEMA IF NOT EXISTS "{self._schema}"')
            await self._conn.execute(
                f'SET search_path TO "{self._schema}"')
        await self._conn.commit()

    def _set_search_path(self) -> None:
        if self._schema and self._conn is not None:
            # connection 级 search_path 已在 _connect 设置;单次 execute 前无需重复
            pass

    async def execute(self, sql: str, params: tuple = (), *, need_lastrowid: bool = False) -> StorageCursor:
        await self._connect()
        sql = _normalize_ddl(sql)
        sql, needs_returning = _rewrite_insert(sql, need_lastrowid)
        sql = _translate_placeholders(sql)
        cur = self._conn.cursor()
        if needs_returning:
            await cur.execute(sql, params)
            row = await cur.fetchone()
            lastrowid = int(row[0]) if row else None
            return _PgCursor(cur, lastrowid=lastrowid)
        await cur.execute(sql, params)
        return _PgCursor(cur)

    async def executemany(self, sql: str, seq_of_params: list[tuple]) -> None:
        await self._connect()
        sql = _translate_placeholders(_normalize_ddl(sql))
        cur = self._conn.cursor()
        await cur.executemany(sql, seq_of_params)
        await self._conn.commit()

    async def executescript(self, script: str) -> None:
        """多语句脚本(DDL)。psycopg 单次 execute 可跑多语句(非参数化)。"""
        await self._connect()
        script = _normalize_ddl(script)
        # 去掉只含分号/空白的尾部(避免空语句报错)
        cleaned = _strip_trailing_semicolons(script)
        if cleaned.strip():
            await self._conn.execute(cleaned)
        await self._conn.commit()

    async def commit(self) -> None:
        if self._conn is not None:
            await self._conn.commit()

    async def close(self) -> None:
        """无操作:保留缓存连接(store 每操作调用,避免断连)。"""

    async def dispose(self) -> None:
        if self._conn is not None and not self._conn.closed:
            await self._conn.close()
        self._conn = None


def _strip_trailing_semicolons(script: str) -> str:
    """去掉脚本尾部悬空分号(psycopg 对尾部空语句报错)。"""
    return re.sub(r"[\s;]*$", "", script)


__all__ = ["PostgresBackend", "_normalize_ddl", "_rewrite_insert"]
